<%
  Dim emotion(24)

  emotion(0) = Array(":)", "happy", "E1.gif")
  emotion(1) = Array(":*", "kiss", "E20.gif")
  emotion(2) = Array(";)", "wink", "E13.gif")
  emotion(3) = Array(">(", "angry", "E18.gif")
  emotion(4) = Array(":'(", "cry", "E12.gif")
  emotion(5) = Array(":o", "shocked", "E11.gif")
  emotion(6) = Array(":P", "tongue", "E10.gif")
  emotion(7) = Array(":p", "tongue", "E10.gif")
  emotion(8) = Array(";P", "tongue", "E16.gif")
  emotion(9) = Array(";p", "tongue", "E16.gif")
  emotion(10) = Array("8-)", "cool", "E7.gif")
  emotion(11) = Array(":-D", "big smile", "E17.gif")
  emotion(12) = Array(":-(", "sad", "E2.gif")
  emotion(13) = Array(":-)", "happy", "E14.gif")
  emotion(14) = Array(";-)", "happy wink", "E9.gif")
  emotion(15) = Array(":D", "big smile", "E9.gif")
  emotion(16) = Array("8)", "cool", "E8.gif")
  emotion(17) = Array("}>", "devil", "E21.gif")
  emotion(18) = Array(";D", "big grin", "E4.gif")
  emotion(19) = Array(":-o", "shocked", "E3.gif")
  emotion(20) = Array(":-P", "tongue", "E15.gif")
  emotion(21) = Array("^_^", "smile", "E9.gif")
  emotion(22) = Array(":-p", "tongue", "E15.gif")
  emotion(23) = Array("???", "confused", "E19.gif")
  emotion(24) = Array(":(", "sad", "E2.gif")
%>